services:

  gitguru-v2:
    build:
      context: .
      dockerfile: Dockerfile
    # image: ghci.io/re-juvenate/gitguru-v2-backend:latest
    depends_on:
      - searxng
      - ollama
      - pmd
    ports:
      - ${PORT_GITGURU}:5555
  
  pmd:
    build:
      context: .
      dockerfile: Dockerfile.pmd    

  searxng:
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ${DATA}/searxng:/etc/searxng:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
      - UWSGI_WORKERS=${SEARXNG_UWSGI_WORKERS:-4}
      - UWSGI_THREADS=${SEARXNG_UWSGI_THREADS:-4}
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  ollama:
    image: ollama/ollama:latest
    ports:
      - ${PORT_OLLAMA}:11434
    volumes:
      - ${DATA}/ollama:/root/.ollama
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: serve
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
  
  # megalinter:
  #   image: oxsecurity/megalinter:v8
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:rw
  #     - ${DATA}/megalinter:/tmp/lint:rw
  #   restart: unless-stopped 
    
  
